---
- name: setup KinD host
  hosts: all
  remote_user: root
  tasks:

  - name: set hostname
    hostname:
      name: "{{ inventory_hostname }}"

#  - name: update rpms
#    yum:
#      name: '*'
#      state: latest
#      disablerepo: docker-ce-stable,kubernetes
#    notify:
#      - os_reboot
#      - os_reboot_wait

  - name: install demo RPMs
    yum:
      name:
        - bind-utils
        - bridge-utils
        - tcpdump
        - bash-completion
      state: latest

  - name: enable firewalld
    service:
      name: firewalld
      enabled: true
      state: started

  - name: Copy /etc/sysctl.d/ipv6.conf
    copy:
      content: "net.ipv6.conf.all.disable_ipv6 = 1"
      dest: /etc/sysctl.d/ipv6.conf

  - name: add sysctl file
    copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        vm.swappiness = 10
      dest: /etc/sysctl.d/k8s.conf
    notify:
      - sysctl_reload

  - name: get docker ce repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/

  - name: install docker-ce rpm
    yum:
      name:
        - docker-ce
      state: installed
      disable_gpg_check: false

  - name: start docker
    service:
      name: docker
      enabled: true
      state: started

  - name: create /root/bin dir
    file:
      path: /root/bin
      state: directory

  - name: install kind
    get_url:
      url: "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64"
      dest: /root/bin/kind
      mode: 0755

  - name: install kubectl
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
      dest: /root/bin/kubectl
      mode: 0755

  - name: add kubectl bash completion
    lineinfile:
      path: /root/.bash_profile
      line: 'source <(kubectl completion bash)'

  - name: copy envvars.txt
    copy:
      src: files/envvars.txt
      dest: /root/envvars.txt

  - name: remove anaconda-ks.cfg
    file:
      path: /root/anaconda-ks.cfg
      state: absent

  handlers:
  - name: remove_swap
    command:
      cmd: swapoff -a

  - name: sysctl_reload
    command:
      cmd: sysctl --system

  - name: systemctl_daemon_reload
    command:
      cmd: systemctl daemon-reload

  - name: os_reboot
    command:
      cmd: reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: os_reboot_wait
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      delay: 15
    delegate_to: localhost

- name: setup Cluster API demo
  hosts: all
  remote_user: root
  tasks:

  - name: create demo dir
    file:
      path: /root/demo
      state: directory

  - name: copy demo YAMLs
    copy:
      src: files/yelb.yml
      dest: /root/demo/yelb.yml

